"""Pydantic models used by the Query Optimizer Agent. This is to structure the 
request and the comparison and all the things in the model"""

from pydantic import BaseModel, Field # type: ignore

from src.models.statistics.query_stats_model import QueryStats


# ==========================================================
# Requests
# ==========================================================

class OptimizationRequest(BaseModel):
    """Request to optimize a SQL query."""

    query: str = Field(
        min_length=1,
        description="SQL query that should be optimized",
    )


class CostComparisonRequest(BaseModel):
    """Request to compare original and optimized queries."""

    original_query: str = Field(
        min_length=1,
        description="Original SQL query",
    )

    optimized_query: str = Field(
        min_length=1,
        description="Optimized SQL query",
    )


# ==========================================================
# Optimization Results
# ==========================================================

class OptimizationResult(BaseModel):
    """AI-generated optimization result."""

    original_query: str

    optimized_query: str

    explanation: str

    index_recommendations: list[str] = Field(
        default_factory=list,
        description="Suggested indexes generated by the AI",
    )


# ==========================================================
# Cost Comparison
# ==========================================================

class CostComparisonResult(BaseModel):
    """Comparison between original and optimized execution plans."""

    startup_cost_before: float = Field(
        ge=0,
    )

    startup_cost_after: float = Field(
        ge=0,
    )

    total_cost_before: float = Field(
        ge=0,
    )

    total_cost_after: float = Field(
        ge=0,
    )

    estimated_rows_before: int = Field(
        ge=0,
    )

    estimated_rows_after: int = Field(
        ge=0,
    )

    improvement_percent: float


# ==========================================================
# Slow Queries
# ==========================================================

class SlowQueriesResult(BaseModel):
    """Top slow queries collected from pg_stat_statements."""

    queries: list[QueryStats]


# ==========================================================
# DeepSeek Response
# ==========================================================

class LLMOptimizationResponse(BaseModel):
    """
    Internal validation model for DeepSeek responses.

    This model is never exposed through the API.
    """

    optimized_query: str

    explanation: str

    index_recommendations: list[str] = Field(
        default_factory=list,
    )