from pydantic import BaseModel #type: ignore


class InvestigationPlan(BaseModel):
    """
    Plan generated by the planner agent.

    Determines:
    - relevant tables
    - relevant metrics
    - relevant dimensions
    """

    question: str
    tables: list[str]
    metrics: list[str]
    dimensions: list[str]