"""API Endpoints for DBVoyager Automated Health Scans & Fix Engine."""

import logging
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, HTTPException, status #type:ignore
from pydantic import BaseModel, Field

from src.services.health.fix_service import HealthFixEngine
from src.services.health.health_summary import HealthSummaryService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/health", tags=["Database Health & Fix Engine"])


# ------------------------------------------------------------------
# Request & Response Schemas
# ------------------------------------------------------------------

class ApplyFixRequest(BaseModel):
    sql_script: str = Field(..., description="The PostgreSQL statements to execute.")
    db_name: Optional[str] = Field(None, description="Target database name.")

class ScanResponse(BaseModel):
    status: str
    health_score: int
    findings_count: int
    proposed_fixes: List[Dict[str, Any]]

class ApplyFixResponse(BaseModel):
    success: bool
    message: str


# ------------------------------------------------------------------
# Endpoints
# ------------------------------------------------------------------

@router.post("/scan", response_model=ScanResponse, status_code=status.HTTP_200_OK)
def trigger_health_scan(db_name: Optional[str] = None):
    """
    Triggers an immediate database health scan. 
    Calculates score, generates proposed SQL fixes, and logs executive reports.
    """
    try:
        engine = HealthFixEngine(db_name=db_name)
        result = engine.run_automated_health_scan()
        
        if result.get("status") == "error":
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=result.get("message", "Failed to run health scan.")
            )
            
        return result
    except Exception as exc:
        logger.error("Error in trigger_health_scan endpoint: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail=str(exc)
        )


@router.post("/apply-fix", response_model=ApplyFixResponse)
def apply_proposed_fix(payload: ApplyFixRequest, connection_provider: Any = None):
    """
    Executes a user-approved SQL fix generated by the AI engine.
    Uses autocommit mode to safely support VACUUM and CREATE INDEX CONCURRENTLY.
    """
    if not payload.sql_script.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="SQL script cannot be empty."
        )

    try:
        # Note: Pass your actual DB connection pool/provider function here
        # E.g., connection_provider = lambda: get_db_connection(payload.db_name)
        if connection_provider is None:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Database connection provider is not configured."
            )

        success = HealthFixEngine.apply_fix_and_commit(
            connection_provider=connection_provider, 
            sql_script=payload.sql_script
        )
        
        return ApplyFixResponse(
            success=success,
            message="SQL fix executed and committed successfully."
        )
    except Exception as exc:
        logger.error("Failed to apply proposed fix: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Execution failed: {str(exc)}"
        )


@router.get("/summary-label")
def get_health_label(score: int):
    """
    Translates a numeric health score (0-100) into a non-technical manager status label.
    """
    if score < 0 or score > 100:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="Score must be between 0 and 100."
        )

    label = HealthSummaryService.get_status_label(score)
    return {"score": score, "status_label": label}