import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { authFetch, authJson } from '../lib/auth';
import { invalidateResource } from '../lib/resourceCache';
import { DataTable, useToast } from '../components/ui';
import { useHeaderSearch } from '../AppShell';

type Connection = { connection_id: string; display_name: string; archived_at?: string | null };
type Report = { report_id: string; question: string; generated_sql: string; result: { columns: string[]; rows: Record<string, unknown>[]; row_count: number }; insight: { summary: string; evidence: string[]; recommendations: string[] }; charts: { title: string; y_axis: string }[] };
type ReportItem = Pick<Report, 'report_id' | 'question'> & { is_pinned: boolean };
type Run = { question: string; stages: Record<string, string>; sql: string; rowCount: number | null; insight: string };
type Row = Record<string, unknown>;
const stages = [['schema', 'Reading schema'], ['plan', 'Planning'], ['sql', 'Generating SQL'], ['validate', 'Safety check'], ['execute', 'Sampling data'], ['analyze', 'Writing insight']];
const icon = (name: string, className = '') => <span aria-hidden="true" className={`material-symbols-outlined ${className}`}>{name}</span>;
const api = <T,>(path: string, init?: RequestInit, force = false) => authJson<T>(path, init, force);

async function consumeSse(response: Response, onEvent: (event: string, data: Row) => void) {
  if (!response.body) throw new Error('Streaming is unavailable.');
  const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = '';
  while (true) { const part = await reader.read(); if (part.done) return; buffer += decoder.decode(part.value, { stream: true }); const messages = buffer.split('\n\n'); buffer = messages.pop() || ''; for (const message of messages) { const event = message.match(/^event: (.+)$/m)?.[1], raw = message.match(/^data: (.+)$/m)?.[1]; if (event && raw) onEvent(event, JSON.parse(raw) as Row); } }
}

export default function BiChatPage() {
  const [params, setParams] = useSearchParams(); const { query } = useHeaderSearch(); const { showToast } = useToast(); const [connections, setConnections] = useState<Connection[]>([]); const [connectionId, setConnectionId] = useState(''); const [reports, setReports] = useState<ReportItem[]>([]); const [active, setActive] = useState<Report | null>(null); const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false); const [run, setRun] = useState<Run | null>(null); const [error, setError] = useState('');
  useEffect(() => { void api<{ data: Connection[] }>('/connections').then(result => { const available = result.data.filter(item => !item.archived_at), requested = params.get('connection'); setConnections(available); setConnectionId(available.some(item => item.connection_id === requested) ? requested || '' : available[0]?.connection_id || ''); }).catch(reason => setError(reason.message)); }, [params]);
  const loadReports = async (force = false) => { if (!connectionId) return; try { setReports((await api<{ data: ReportItem[] }>(`/connections/${connectionId}/bi/reports`, undefined, force)).data); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load reports.'); } };
  useEffect(() => { void loadReports(); setActive(null); }, [connectionId]); // eslint-disable-line react-hooks/exhaustive-deps
  const matchedReports = useMemo(() => reports.filter(item => !query || item.question.toLowerCase().includes(query.toLowerCase())), [reports, query]);
  const pinned = useMemo(() => matchedReports.filter(item => item.is_pinned), [matchedReports]);
  async function ask(event: React.FormEvent) { event.preventDefault(); const asked = question.trim(); if (!asked || loading || !connectionId) return; setLoading(true); setError(''); setActive(null); setQuestion(''); setRun({ question: asked, stages: Object.fromEntries(stages.map(([id]) => [id, 'pending'])), sql: '', rowCount: null, insight: '' }); try { const response = await authFetch(`/connections/${connectionId}/bi/investigations/stream`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: asked }) }); if (!response.ok) throw new Error('Investigation failed.'); await consumeSse(response, (eventName, data) => { if (eventName === 'stage') setRun(current => current ? { ...current, stages: { ...current.stages, [String(data.stage)]: String(data.status) } } : current); else if (eventName === 'sql_ready') setRun(current => current ? { ...current, sql: String(data.sql || '') } : current); else if (eventName === 'results_ready') setRun(current => current ? { ...current, rowCount: Number(data.row_count || 0) } : current); else if (eventName === 'insight_delta') setRun(current => current ? { ...current, insight: current.insight + String(data.text || '') } : current); else if (eventName === 'complete') { setActive(data as unknown as Report); setRun(null); invalidateResource(`/connections/${connectionId}/bi/reports`); void loadReports(true); } else if (eventName === 'error') throw new Error(String(data.message || 'Investigation failed.')); }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Investigation failed.'); } finally { setLoading(false); } }
  async function open(id: string) { try { setActive(await api<Report>(`/connections/${connectionId}/bi/reports/${id}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not open report.'); } }
  async function pin(item: ReportItem) { try { await api(`/connections/${connectionId}/bi/reports/${item.report_id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_pinned: !item.is_pinned }) }); invalidateResource(`/connections/${connectionId}/bi/reports`); await loadReports(true); showToast({ tone: 'success', message: item.is_pinned ? 'Report unpinned.' : 'Report pinned.' }); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Could not update report.'; setError(message); showToast({ tone: 'error', message }); } }
  return <section className="mx-auto max-w-6xl p-6 pb-40 md:p-10 md:pb-40"><header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-xs tracking-[.16em] text-voyager-blue">READ-ONLY BI INVESTIGATOR</p><h1 className="mt-2 font-display text-3xl font-semibold">BI Navigator</h1></div><select value={connectionId} onChange={event => { setConnectionId(event.target.value); setParams({ connection: event.target.value }); }} className="ui-input m-0 w-auto" aria-label="Selected database">{connections.map(connection => <option value={connection.connection_id} key={connection.connection_id}>{connection.display_name}</option>)}</select></header>{error && <p role="alert" className="mb-5 border border-red-400/40 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}<div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><main className="min-w-0">{run ? <InvestigationRun run={run} /> : active ? <ReportView report={active} /> : <EmptyChat />}</main><aside className="voyager-card h-fit p-4"><ReportList title="Pinned reports" items={pinned} onOpen={open} onPin={pin} /><ReportList title="Recent reports" items={matchedReports.filter(item => !item.is_pinned)} onOpen={open} onPin={pin} /></aside></div><form onSubmit={ask} className="fixed bottom-0 left-0 right-0 border-t border-voyager-border bg-voyager-navy/95 p-4 md:left-[240px]"><div className="mx-auto flex max-w-6xl gap-2"><input disabled={loading} value={question} onChange={event => setQuestion(event.target.value)} className="ui-input m-0 flex-1" placeholder="Ask Voyager to analyze your data..." /><button disabled={loading || !question.trim()} className="ui-button ui-button-primary">{loading && icon('progress_activity', 'animate-spin')}Send</button></div><div className="mx-auto mt-2 flex max-w-6xl gap-4 text-xs text-voyager-text-secondary"><button type="button" onClick={() => setQuestion('Compare this to last quarter')}>Compare to last quarter</button><Link to={`/health-checks?connection=${connectionId}`}>Run anomaly check</Link></div></form></section>;
}

function ReportList({ title, items, onOpen, onPin }: { title: string; items: ReportItem[]; onOpen: (id: string) => Promise<void>; onPin: (item: ReportItem) => Promise<void> }) { return <section className="mb-5 last:mb-0"><p className="mb-2 font-mono text-xs tracking-widest text-voyager-text-secondary">{title.toUpperCase()}</p>{items.length ? items.map(item => <div key={item.report_id} className="flex items-center gap-2 py-2 text-sm"><button className="min-w-0 flex-1 truncate text-left hover:text-voyager-blue-light" onClick={() => void onOpen(item.report_id)}>{item.question}</button><button className="ui-icon-button min-h-0 size-7" onClick={() => void onPin(item)} aria-label="Toggle pin">{icon(item.is_pinned ? 'push_pin' : 'keep')}</button></div>) : <p className="text-sm text-voyager-text-secondary">No reports yet.</p>}</section>; }
function EmptyChat() { return <div className="voyager-card grid min-h-[42vh] place-items-center p-6 text-center"><div><h2 className="font-display text-2xl">Ask a business question.</h2><p className="mt-3 text-sm text-voyager-text-secondary">Results, SQL, evidence, and charts are saved to this connection’s report history.</p></div></div>; }
function InvestigationRun({ run }: { run: Run }) { return <article className="voyager-card p-5" aria-live="polite"><p className="text-right text-sm text-voyager-text-secondary">{run.question}</p><h2 className="mt-5 font-display text-xl">Voyager is working safely</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{stages.map(([id, label]) => <div key={id} className="border border-voyager-border p-3 text-sm"><span className={run.stages[id] === 'running' ? 'animate-pulse text-voyager-blue-light' : ''}>{run.stages[id] === 'complete' ? '✓' : '○'} {label}</span></div>)}</div>{run.sql && <details className="mt-5 border border-voyager-border bg-voyager-navy2 p-3 text-sm"><summary>Validated read-only SQL</summary><pre className="mt-3 overflow-auto text-voyager-blue-light">{run.sql}</pre></details>}{run.rowCount !== null && <p className="mt-4 text-sm text-emerald-300">{run.rowCount} safe sample rows ready for analysis.</p>}{run.insight && <p className="mt-4 whitespace-pre-wrap text-sm text-voyager-text-secondary">{run.insight}</p>}</article>; }
function ReportView({ report }: { report: Report }) { return <article className="voyager-card p-5"><h2 className="font-display text-xl">{report.question}</h2><p className="mt-4 text-voyager-text-secondary">{report.insight.summary}</p><pre className="mt-5 overflow-auto border border-voyager-border bg-voyager-navy2 p-4 text-sm text-voyager-blue-light">{report.generated_sql}</pre><div className="mt-5"><DataTable<Record<string, unknown>> columns={report.result.columns.map(column => ({ id: column, header: column, cell: row => String(row[column] ?? '—'), sortValue: row => String(row[column] ?? '') }))} rows={report.result.rows} rowKey={(_, index) => String(index)} /></div></article>; }
